---
- name: Get device uptime
  hosts:
    - juniper_srx
  connection: local
  gather_facts: no

  vars_prompt:
    - name: username
      prompt: Junos username
      private: no

    - name: password
      prompt: Junos password
      private: yes

  tasks:
    - name: get uptime using ansible core module
      junos_rpc:
        rpc: get-system-uptime-information
        output: xml
        provider:
          host: "{{ ansible_host }}"
          port: 22
          username: "{{ username }}"
          password: "{{ password }}"
      register: uptime

    - name: display uptime
      debug: var=uptime
